# Generated by Django 6.0.4 on 2026-05-05 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('species', models.CharField(choices=[('pies', 'Pies'), ('kot', 'Kot')], max_length=10, verbose_name='Gatunek')),
                ('age', models.PositiveIntegerField(verbose_name='Wiek (w latach)')),
                ('size', models.CharField(choices=[('mały', 'Mały'), ('średni', 'Średni'), ('duży', 'Duży')], max_length=10, verbose_name='Wielkość')),
                ('description', models.TextField(verbose_name='Opis')),
                ('status', models.CharField(choices=[('available', 'Dostępny'), ('pending', 'W trakcie adopcji'), ('adopted', 'Adoptowany')], default='available', max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Zdjęcie')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa schroniska')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('address', models.TextField(verbose_name='Adres')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('experience', models.TextField(blank=True, verbose_name='Doświadczenie ze zwierzętami')),
                ('living_conditions', models.TextField(blank=True, verbose_name='Warunki mieszkaniowe')),
                ('status', models.CharField(choices=[('new', 'Nowe zgłoszenie'), ('review', 'W analizie'), ('approved', 'Zatwierdzone'), ('rejected', 'Odrzucone')], default='new', max_length=20, verbose_name='Status wniosku')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Aplikujący')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.animal', verbose_name='Zwierzę')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='core.shelter', verbose_name='Schronisko'),
        ),
    ]
